# Generated by Django 5.1 on 2024-08-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="measuring_system_preference",
            field=models.IntegerField(
                choices=[(0, "Metric"), (1, "Imperial")], default=1
            ),
        ),
    ]
