# Generated by Django 5.1 on 2024-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_remove_instruction_time_start"),
        ("users", "0002_profile_measuring_system_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="favourite",
            field=models.ManyToManyField(to="recipes.recipe"),
        ),
    ]
