# Generated by Django 5.1 on 2024-08-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_remove_instruction_time_start"),
        ("users", "0003_profile_favourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tobake",
            field=models.ManyToManyField(
                related_name="tobake_recipes", to="recipes.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="favourite",
            field=models.ManyToManyField(
                related_name="favourite_recipes", to="recipes.recipe"
            ),
        ),
    ]
