# Generated by Django 5.1 on 2024-08-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_tobake_alter_profile_favourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default="17057@learning.gsis.edu.hk", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
