# Generated by Django 5.1 on 2024-08-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
