# Generated by Django 5.1 on 2024-08-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default="17057@learning.gsis.edu.hk", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
