# Generated by Django 5.1 on 2025-03-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
