# Generated by Django 5.1 on 2024-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="intended_serving_size",
            field=models.IntegerField(),
        ),
    ]
