# Generated by Django 5.1 on 2024-08-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_intended_serving_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="measuring_system",
            field=models.IntegerField(
                choices=[(0, "Metric"), (1, "Imperial")], default=1
            ),
        ),
    ]
