# Generated by Django 5.1 on 2024-08-12 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_measuring_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(default="Description to be added..."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(default="default-slug"),
            preserve_default=False,
        ),
    ]
