# Generated by Django 5.1 on 2024-08-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_date_created_recipe_description_recipe_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
