# Generated by Django 5.1 on 2024-08-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
