# Generated by Django 5.1 on 2024-08-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_instruction_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="uom",
            field=models.IntegerField(
                choices=[
                    (0, "cup"),
                    (1, "tbsp"),
                    (2, "tsp"),
                    (3, "oz"),
                    (4, "lbs"),
                    (5, "stick"),
                    (6, "ml"),
                    (7, "g"),
                    (8, ""),
                ],
                default=8,
            ),
        ),
    ]
