# Generated by Django 5.1 on 2024-08-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_instruction_time_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="description",
        ),
    ]
