# Generated by Django 5.1 on 2024-08-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_remove_recipe_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instruction",
            name="time_start",
        ),
    ]
