# Generated by Django 5.1 on 2024-11-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_remove_instruction_time_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="timer_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
